import { AIGeneration, CheckIn } from "@/types/entities";

// Mock AI-generated content for demo
export const mockAIGenerations: AIGeneration[] = [
  {
    id: "ai-1",
    type: "summary",
    clientId: "client-1",
    sessionId: "session-1",
    content: `## Session Summary - Leadership Development

### Key Topics Discussed
- Challenges with delegating tasks to team members
- Building confidence in decision-making
- Managing imposter syndrome in new leadership role

### Client Progress
Sarah showed significant growth in recognizing her delegation patterns. She successfully identified 3 tasks she can delegate this week.

### Action Items
1. Delegate the weekly report preparation to direct report
2. Practice "pause before responding" technique in meetings
3. Journal about leadership wins at end of each day

### Coach Notes
Sarah is making excellent progress. Consider introducing the GROW model in next session for structured goal-setting.

*Generated by Coaching OS AI*`,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: "ai-2",
    type: "summary",
    clientId: "client-2",
    sessionId: "session-3",
    content: `## Session Summary - Career Transition

### Key Topics Discussed
- Updating resume for tech industry pivot
- Networking strategy for target companies
- Managing anxiety about career change at 35

### Client Progress
Michael has completed his LinkedIn profile optimization and received positive feedback from 2 connections in target industry.

### Action Items
1. Schedule 3 informational interviews this week
2. Complete online Python course module 4
3. Research 5 companies aligned with values

### Coach Notes
Michael's confidence is growing. His analytical skills will transfer well. Consider focusing on story-telling for interviews next session.

*Generated by Coaching OS AI*`,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: "ai-3",
    type: "homework",
    clientId: "client-1",
    content: `## Suggested Homework for Sarah

Based on your leadership development program and recent progress:

### Weekly Practices
1. **Daily Leadership Journal** (10 min)
   Write about one leadership decision you made and its outcome

2. **Delegation Tracker**
   Track tasks delegated, outcomes, and lessons learned

3. **Confidence Affirmations**
   Review 3 leadership strengths each morning

### Reading Assignment
- "The Making of a Manager" by Julie Zhuo, Chapter 4

### Reflection Questions
- What leadership style do I naturally gravitate toward?
- Where am I holding myself back from delegating?

*Generated by Coaching OS AI*`,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "ai-4",
    type: "checkin",
    clientId: "client-3",
    content: `## Weekly Check-in Questions

1. On a scale of 1-10, how would you rate your energy levels this week?

2. What was your biggest win since our last session?

3. What challenges are you currently facing with your morning routine?

4. Have you completed the homework assignments from our last session?

5. What support do you need from me this week?

*Generated by Coaching OS AI*`,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
];

// Mock check-ins from clients
export const mockCheckIns: CheckIn[] = [
  {
    id: "checkin-1",
    clientId: "client-1",
    responses: [
      { question: "How are you feeling about your progress this week?", answer: "I'm feeling more confident about delegating. Successfully handed off the weekly report task!" },
      { question: "What challenges did you face?", answer: "Still struggling with perfectionism when reviewing team's work." },
      { question: "Energy level (1-10)?", answer: "7" },
      { question: "What support do you need?", answer: "Could use some strategies for managing my need to control outcomes." },
    ],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "checkin-2",
    clientId: "client-2",
    responses: [
      { question: "How are you feeling about your progress this week?", answer: "Anxious but excited. Had 2 great informational interviews!" },
      { question: "What challenges did you face?", answer: "Finding time for coding practice with full-time job." },
      { question: "Energy level (1-10)?", answer: "6" },
      { question: "What support do you need?", answer: "Help with time management and prioritization." },
    ],
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
];

// Helper functions
export function getAIGenerationsForClient(clientId: string): AIGeneration[] {
  return mockAIGenerations.filter((gen) => gen.clientId === clientId);
}

export function getCheckInsForClient(clientId: string): CheckIn[] {
  return mockCheckIns.filter((checkin) => checkin.clientId === clientId);
}

export function getLatestCheckIn(clientId: string): CheckIn | undefined {
  const clientCheckIns = mockCheckIns.filter((checkin) => checkin.clientId === clientId);
  return clientCheckIns.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())[0];
}
